### ISSUE TITLE
What does the item "UrineIncontinentie" output volume means?

### ISSUE THREAD

**Issue by arielhasidim** [AmsterdamUMC/AmsterdamUMCdb#95] opened 2023-11-15 07:14 UTC
Dear maintainers,

I hope you are doing well. I am seeking clarification for the item "UrineIncontinentie" in the "numericitems" table. Which type of catheter and the specific body part it is intended for? To provide context, please refer to the following link: [urine_output.sql](https://github.com/AmsterdamUMC/AmsterdamUMCdb/blob/b88795565dae865869e6678c1d836e1e8200f41b/amsterdamumcdb/sql/common/urine_output.sql)

Your assistance in providing more details would be greatly appreciated. Thank you for your time and consideration.

Best regards,
Ariel

**Comment by patrickthoral** [comment] 2023-11-15 11:17
duplicate of #25

**Closed by patrickthoral** 2023-11-15 11:17 UTC
